import { ogImageUrl } from "@/lib/og/url";

/** Canonical host for ProgramBI marketing. Always www. */
export const SITE_URL = "https://www.programbi.com";

export function absoluteUrl(path = "/"): string {
  if (!path || path === "/") return SITE_URL;
  if (path.startsWith("http")) return path;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

export const ORG_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

/** Default share card generated by app/opengraph-image.tsx */
export const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "ProgramBI — Cursos de Análisis de Datos, Power BI, SQL y Python",
} as const;

/** Safe JSON-LD payload (escapes `<` to avoid XSS in script tags). */
export function jsonLdString(data: unknown): string {
  return JSON.stringify(data).replace(/</g, "\\u003c");
}

export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.path.startsWith("http") ? item.path : absoluteUrl(item.path),
    })),
  };
}

/** Twitter card matching an OG image so root layout twitter:image does not leak. */
export function twitterShare(
  title: string,
  description: string,
  imageUrl: string = DEFAULT_OG_IMAGE.url
) {
  return {
    card: "summary_large_image" as const,
    title,
    description,
    images: [imageUrl],
  };
}

/** OG + Twitter pair using the existing /og pipeline (no new card design). */
export function pageOg(opts: {
  title: string;
  description: string;
  path: string;
  kicker: string;
  tags?: string[];
  alt?: string;
}) {
  const url = ogImageUrl({
    kicker: opts.kicker,
    title: opts.title,
    description: opts.description,
    tags: opts.tags,
    path: opts.path.replace(/^\//, ""),
  });
  return {
    images: [
      {
        url,
        width: 1200,
        height: 630,
        alt: opts.alt || opts.title,
      },
    ],
    twitter: twitterShare(opts.title, opts.description, url),
  };
}

export const MONEY_COURSE_SLUGS = [
  "power-bi",
  "analisis-de-datos",
  "analitica-mineria",
] as const;

export const HOME_COURSE_SLUGS = [
  "power-bi",
  "analisis-de-datos",
  "analitica-mineria",
  "sql-server",
  "python",
  "analitica-financiera",
] as const;
